// Lo que hace cada suplemento, en una o dos frases, para la cabecera de su categoria.
//
// Sale del `resumen` de EVIDENCIA (datos/evidencia.js), que es lo revisado contra las
// fuentes: aqui no se afirma NADA que no diga ya la guia, solo se recorta. Si cambia el
// resumen de una guia, se revisa su linea. La cita y los matices estan en /guia/<slug>/,
// que se enlaza justo debajo. Sin tildes, como el resto de datos: las restaura el build.
export const BREVE = {
  'acido-hialuronico': 'Una molecula de la piel y las articulaciones. Tomada por boca hay ensayos pequenos con resultados en arrugas y dolor de rodilla, muchos ligados a fabricantes.',
  arginina: 'Se vende para subir el oxido nitrico y llevar mas sangre al musculo. En la practica rinde poco: el efecto aparece en gente poco entrenada y no en la muy entrenada.',
  ashwagandha: 'Una planta con ensayos que encuentran menos estres percibido y cortisol frente a placebo. Casi todos usan extractos estandarizados, no raiz en polvo.',
  bcaa: 'Tres de los nueve aminoacidos esenciales. Solos no construyen musculo, y si ya llegas a tu proteina del dia no anaden nada.',
  'beta-alanina': 'Sube la carnosina del musculo, que amortigua la acidez en esfuerzos maximos de uno a cuatro minutos. El efecto llega tras semanas tomandola, no con la toma de antes de entrenar.',
  cafeina: 'Retrasa la sensacion de fatiga y mejora el rendimiento desde el primer dia. Se dosifica por peso: 3-6 mg por kilo, con un maximo de 400 mg al dia.',
  calcio: 'El mineral del hueso. Si la dieta ya va razonable, suplementarlo sube poco la densidad osea: primero comida, y el bote solo si la comida no llega.',
  carbohidratos: 'Azucar comodo de beber para sostener el rendimiento en entrenamientos de mas de una hora. Entre maltodextrina, dextrosa y las versiones caras la diferencia practica es pequena.',
  carnitina: 'Transporta la grasa a la mitocondria, pero tomar mas no quema mas grasa: una persona sana ya tiene de sobra. Evidencia limitada en grasa y en rendimiento.',
  caseina: 'La proteina lenta de la leche: libera aminoacidos durante horas. Su uso con respaldo es la toma antes de dormir.',
  citrulina: 'Sube el oxido nitrico mejor que la arginina. A 6-8 g de citrulina malato da unas repeticiones mas en series al fallo; efecto pequeno y no siempre consistente.',
  cla: 'Un acido graso que dio buen resultado en animales. En personas, unos 0,09 kg menos de grasa por semana en el mejor caso, con dudas de seguridad en algunos perfiles.',
  'coenzima-q10': 'Pieza de la produccion de energia de la celula. Su evidencia solida se limita a la insuficiencia cardiaca; en personas sanas que entrenan no mejora el rendimiento.',
  colageno: 'No es proteina para el musculo: le faltan aminoacidos esenciales. Donde hay senal es en tendon, ligamento y cartilago.',
  colina: 'Un nutriente que la mayoria cubre con la dieta. Su forma alfa-GPC se vende para fuerza y enfoque, con resultados solo parciales.',
  'complejo-b': 'Vitaminas que participan en producir energia, pero no la aportan. Corregir un deficit mejora el rendimiento; sumar sobre un estado normal, no.',
  creatina: 'Llena la reserva de energia del musculo para los primeros segundos de un esfuerzo maximo: mas fuerza y mas trabajo por serie. Es el suplemento deportivo con mas evidencia.',
  curcuma: 'Su activo, la curcumina, se absorbe mal y por eso va con piperina. Alivia el dolor articular en ensayos cortos y pequenos: prometedor, no concluyente.',
  eaa: 'Los nueve aminoacidos esenciales, los que activan la sintesis de musculo. Mejor que los BCAA, pero una whey ya los lleva todos y cuesta menos por toma.',
  espirulina: 'Un alga que se vende como superalimento, con apenas un ensayo pequeno en rendimiento. Su B12 no sirve como B12 y el control del lote importa mucho.',
  'ganador-peso': 'Comida en polvo para sumar calorias. No tiene un activo propio: compras comodidad, y el mismo superavit se consigue en la cocina.',
  glucosamina: 'El suplemento articular clasico. El ensayo independiente mas grande, con casi 1.600 pacientes, no encontro diferencia frente a placebo.',
  glutamina: 'El cuerpo la fabrica y la dieta la aporta de sobra. En una persona sana no cambia nada medible en rendimiento ni composicion corporal.',
  hierro: 'Transporta el oxigeno en la sangre y su deficit hunde el rendimiento. No conviene tomarlo por si acaso: primero una analitica.',
  hmb: 'Un derivado de la leucina que se vende para proteger el musculo. Puede tener sentido en quien no entrena o pierde musculo; en deportistas entrenados no muestra efecto.',
  maca: 'Una planta andina que se vende como energizante y para la libido. Hay pocos estudios y pequenos: no se puede decir que funcione, y para rendimiento no hay nada.',
  magnesio: 'Mineral con funciones en musculo, sistema nervioso y cansancio. Lo que cuenta es el magnesio real de cada sal, que cambia mucho entre formas.',
  melatonina: 'La hormona que le dice al cuerpo que es de noche: adelanta el sueno, no te duerme de golpe. Con 1 mg basta; mas dosis no es mas efecto.',
  multivitaminico: 'Corrige carencias, pero no mejora el rendimiento de quien come bien. Para saber si te falta algo, mejor una analitica que un bote.',
  omega3: 'Lo que cuenta es el EPA+DHA, no los mg de aceite del bote: 250 mg al dia de los dos. El aceite se oxida, asi que aqui el sello de calidad importa mucho.',
  potasio: 'Subir su ingesta baja la tension en personas con hipertension. Es un mineral de salud, no de gimnasio: la idea de que evita calambres tiene poca base.',
  preentreno: 'Lo que casi siempre funciona es la cafeina. El resto de activos tienen dosis eficaces conocidas que muchos botes no alcanzan.',
  probioticos: 'El efecto es de cada cepa concreta a una dosis concreta, sobre digestion e infecciones respiratorias. Un bote que no dice la cepa no puede prometer nada.',
  'proteina-aislada': 'La misma proteina de suero que la whey, filtrada mas veces: mas proteina por kilo y casi sin lactosa ni grasa. En el musculo hace lo mismo.',
  'proteina-vegana': 'Hace el mismo trabajo que la whey si tomas algo mas (unos 30 g en vez de 20) o mezclas dos fuentes vegetales. Lo que manda es la proteina total del dia.',
  'proteina-whey': 'Te ayuda a llegar a tu proteina del dia, que es lo que construye musculo. El beneficio deja de crecer hacia 1,6 g por kilo al dia: es comida comoda, no un farmaco.',
  quemagrasas: 'Una mezcla, no un ingrediente: solo la cafeina y el te verde tienen datos a favor. Hay un riesgo real de productos adulterados con farmacos.',
  selenio: 'Necesario para la tiroides y enzimas antioxidantes, en cantidades muy pequenas: 55 microgramos al dia. El margen hasta pasarse es estrecho.',
  taurina: 'Un aminoacido del musculo y el corazon, no un estimulante. Mejora algo el rendimiento de resistencia; mas dosis o mas semanas no mejoran el resultado.',
  'te-verde': 'El extracto se vende para perder grasa con evidencia floja y contradictoria. Por encima de 800 mg de EGCG al dia se han visto subidas de las enzimas del higado.',
  teanina: 'Un aminoacido del te verde que baja algo el estres y mejora el sueno. Con cafeina mejora la atencion y le quita las aristas.',
  tribulus: 'Se vende para subir la testosterona y los ensayos no lo confirman: ni mas testosterona, ni mas fuerza, ni mas masa magra frente a placebo.',
  triptofano: 'Precursor de la serotonina y la melatonina. Para dormir hay un efecto pequeno y concreto; para la depresion, la evidencia es muy pobre.',
  'vitamina-b12': 'La unica vitamina que una dieta 100 % vegetal no da de forma fiable. Su deficit tarda anos en aparecer y puede dejar dano neurologico: en dieta vegana es parte de la dieta.',
  'vitamina-c': 'Necesaria para el colageno, las defensas y la absorcion del hierro. Tomarla a diario no evita resfriados; solo acorta un poco su duracion.',
  'vitamina-d': 'La fabrica la piel con el sol, y por eso falta a quien pasa el dia en interiores. Papel en huesos, musculos y defensas. Ojo a las unidades: microgramos o UI.',
  'vitamina-e': 'Un antioxidante necesario cuyo deficit es raro con dieta normal. Lo importante es no pasarse: a dosis altas se asocia a mas mortalidad.',
  'vitamina-k2': 'Necesaria para la coagulacion y el hueso: en su mejor ensayo redujo parte del descenso de densidad osea. No tiene evidencia deportiva e interactua con anticoagulantes.',
  zinc: 'Participa en las defensas y en mantener niveles normales de testosterona, que no es subirlos. Si ya tomas suficiente, anadir mas no cambia nada.',
  zma: 'Zinc, magnesio y vitamina B6 juntos. En deportistas entrenados no se vio cambio en la testosterona ni en el progreso: util solo si te falta alguno.',
};
